version: '3.8'

services:
    photos-api:
        container_name: photos-api
        user: 'node'
        restart: unless-stopped
        command: 'npm start'
        ports:
            - 5050:5050
        volumes:
            - ./Omega-Photo-API:/opt/photos-api
            - ./storage:/opt/photos-api/photos
        working_dir: /opt/photos-api
        image: node:17.2.0-alpine
        privileged: true
    python-api:
        container_name: python-api
        restart: unless-stopped
        command: 'python src/main.py'
        env_file: .env
        image: omega-project_python-api:latest
        ports:
            - 5000:5000
        volumes:
            - ./project_omega:/opt/python-api
            - ./storage:/opt/python-api/photos
        working_dir: /opt/python-api
        privileged: true

volumes:
  storage:
        driver: local
        driver_opts:
            type: none
            device: .
            o: uid=<UID>,gid=<GID>